version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g yarn
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - yarn install
  build:
    commands:
      - yarn run generate
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - /tmp/node_modules.tar
